# Generated by Django 2.1.4 on 2019-01-01 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Djeddit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='num_vote_down',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='num_vote_up',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='vote_score',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='moderators',
            field=models.ManyToManyField(blank=True, related_name='mod_subscriptions', to='Djeddit.Subreddit'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='subscriptions',
            field=models.ManyToManyField(blank=True, related_name='sub_subscriptions', to='Djeddit.Subreddit'),
        ),
        migrations.AlterField(
            model_name='subreddit',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
